import argparse

parser = argparse.ArgumentParser(description='VadCLIP')
parser.add_argument('--seed', default=214, type=int)

parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=2, type=int)
parser.add_argument('--visual-layers-1', default=1, type=int)
parser.add_argument('--audio-length', default=256, type=int)
parser.add_argument('--audio-width', default=512, type=int)
parser.add_argument('--attn-window', default=4, type=int)
parser.add_argument('--attn-window-1', default=64, type=int)
parser.add_argument('--prompt-prefix', default=10, type=int)
parser.add_argument('--prompt-postfix', default=10, type=int)
parser.add_argument('--classes-num', default=7, type=int)

parser.add_argument('--max-epoch', default=10, type=int)
parser.add_argument('--model-path-t', default='../model/model_cctv_t.pth')
parser.add_argument('--model-path-s', default='../model/model_cctv_s.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path-t', default='../model/checkpoint_cctv_t.pth')
parser.add_argument('--checkpoint-path_s', default='../model/checkpoint_cctv_s.pth')
parser.add_argument('--batch-size', default=96, type=int)
parser.add_argument('--train-list', default='../list/cctv_CLIP_rgb.csv')
parser.add_argument('--test-list', default='../list/cctv_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='../list/gt_cctv.npy')
parser.add_argument('--gt-segment-path', default='../list/gt_cctv_segment.npy')
parser.add_argument('--gt-label-path', default='../list/gt_cctv_label.npy')

parser.add_argument('--lr', default=1e-5)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[3, 6, 10])